# Generated by Django 5.0.3 on 2024-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ABANDONED', 'Abandoned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], max_length=20)),
            ],
        ),
    ]
