# Generated by Django 5.0.4 on 2024-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_todo',
            name='status',
        ),
        migrations.AddField(
            model_name='task_todo',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mieszkanie'), (2, 'Ogród')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='task_todo',
            name='subcategory',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sypialnia'), (2, 'Łazienka')], default=1, null=True),
        ),
    ]
