# Generated by Django 5.0.3 on 2024-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_todo',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ABANDONED', 'Abandoned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NEW', max_length=20),
        ),
    ]
