# Generated by Django 5.0.4 on 2024-04-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0002_task_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
