# Generated by Django 5.0.4 on 2024-04-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task_todo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
