# Generated by Django 5.0.4 on 2024-04-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0004_task_todo_is_active_task_todo_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_todo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='task_todo',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
