# Generated by Django 5.0.4 on 2024-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_app', '0005_remove_task_todo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
